Repository vtex-apps/store-theme, pull requests merged in 2018-08, with the labels that each got.

#64 Impersonating a customer
  CHANGELOG.md
  manifest.json
  pages/pages.json
Labels: enhancement

#72 Fix carousel position in home page
  CHANGELOG.md
  manifest.json
  pages/pages.json
Labels: bug

#74 Bump version of vtex.store-components and vtex.styleguide
  CHANGELOG.md
  manifest.json
Labels: dependency-change
